import "../app/globals.css";
import { Inter } from "next/font/google";
import "./globals.css";
import toast from "react-hot-toast";
import { Metadata } from "next";
import { ToasterProvider } from "@/components/ui/providers/toaster-provider";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

const inter = Inter({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "LMS-Nextjs",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ToasterProvider />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
